### ISSUE TITLE
Residuals comparing with C. Stark's IDL implementation larger in Y direction

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/jwxml#4]
I'm not sure if this is a bug in either code, just an acceptable consequence of not performing arbitrary-precision arithmetic, or what... so I'm making an issue that can be closed if the consequences of this discrepancy are small enough that we don't care.

There's code in Chris Stark's IDL visibility checker that goes from (V2, V3) to ideal frame, to science frame, then finally to the detector frame. The same transformations on the same inputs with `jwxml` `SIAF` and `Aperture` classes show good (< 0.01 px) agreement, but the residuals are notably larger in detector Y than in X. See the attached plot of residuals.

![unknown](https://cloud.githubusercontent.com/assets/172886/13334060/ff57f432-dbd7-11e5-867f-aa4957d622cc.png)

(The box is drawn at the "absolute tolerance" epsilon I chose to make the tests pass: 1.2e-3.)

**Comment by josePhoenix** [comment]
Update: increased the tolerance to 1.3e-3 to get the rest of the Fomalhaut case passing.

**Comment by mperrin** [comment]
This is probably a question for Lallo & Cox. I have no particular insight into what tolerances should be achieved here. Though 1e-3 certainly sounds a lot higher than machine precision...

**Comment by mperrin** [comment]
I remember some emails about this back a while ago. Did you ever work out what the deal was? Is this something that still warrants being kept as an open issue?   (not an urgent question, just something that came across my mind while trying to get organized about other webbpsf stuff)

**Comment by josePhoenix** [comment]
I followed this as far as I could and still couldn't identify the root cause. If we (you) are satisfied with 1/1000th of a pixel agreement, it can be closed.

**Comment by mperrin** [comment]
1/1000th of a pixel is good enough for me!  Maybe not for the craziest ultra precision astrometry that people will be doing many years after launch, but that's a problem for another day. 

It's still weird to not get machine precision agreement from IDL and Python, but there's only so many hours in the day.
