### ISSUE TITLE
jwxml -> PYPI

### ISSUE THREAD

**Issue by mperrin** [mperrin/jwxml#9]
@josePhoenix we were going to put this on pypi as a full package, yes? Were you going to do that or me?  Right now issues with this sub package (submodule?) seem to be what's breaking the webbpsf CI builds.  I think this wasn't a problem before because without the SI WFE code there was nothing trying to exercise the SIAF functionality in the test suite. 

Can you take care of putting this on PyPI, and updating the webbpsf si_wfe branch as needed to invoke that rather than having this in the repo directly? Thanks much.

**Comment by josePhoenix** [comment]
It's on PyPI, so the changes that need to happen are in WebbPSF. I'll take care of those.

Joseph
